version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    image: openjdk:17-slim
    container_name: java-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB1_URL: jdbc:postgresql://postgres-db:5432/testdb
      DB1_USERNAME: testuser
      DB1_PASSWORD: testpass
      DB2_URL: jdbc:mysql://mysql-db:3306/testdb
      DB2_USERNAME: testuser
      DB2_PASSWORD: testpass
    depends_on:
      - postgres-db
      - mysql-db
    ports:
      - "8087:8087"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
  mysql_data:
